### ISSUE TITLE
mock Image with propTypes

### ISSUE THREAD

**Issue by sibelius** [navjobs/jest-snapshot-utils#1]
thanks for this utils tool, it is very handy

When I try to test a component that depends on react-native-router-flux

I got the following error:

```js
Runtime Error
  - TypeError: Cannot read property 'source' of undefined
        at Object.<anonymous> (node_modules/react-native-router-flux/src/NavBar.js:155:45)
        at Object.<anonymous> (node_modules/react-native-router-flux/src/DefaultRenderer.js:21:13)
        at Object.<anonymous> (node_modules/react-native-router-flux/index.js:3:22)
```

this is the line that breaks the test

`backButtonImage: Image.propTypes.source,`

it breaks because Image doesn't have propTypes, how can I fix this?

**Comment by zackify** [comment]
Have you tried jest.mock('Image')? I also use that library, I'll try out
snapshotting some things with its components and see if I get the same
problem. Also I think there was a change to prop types recently? I will
look into it.

**Comment by sibelius** [comment]
jest.unmock('Image') works!

another problem is to mock `Actions.create` of RNRF
